### ISSUE TITLE
Error in SpecFlow.NetCore tool during print messages

### ISSUE THREAD

**Issue by aensidhe** [stajs/SpecFlow.NetCore#65] opened 2018-01-11 14:17 UTC
Version: 1.2.0

Related to https://github.com/techtalk/SpecFlow/issues/1002

I have Windows development machine. Everything is working ok.
I also have Windows build agent. Nothing works :) Log is below. How do I debug/fix this?

````
PS C:\BuildAgent\work\1cdf652514f12572\backend> dotnet --info
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

PS C:\BuildAgent\work\1cdf652514f12572\backend> dotnet build .\tests\services.SpecFlow\services.SpecFlow.csproj
C:\BuildAgent\work\1cdf652514f12572\backend\tests\services.SpecFlow\services.SpecFlow.csproj : warning NU1701: Package 'SpecFlow 2.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the pr
oject target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.


  Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest
definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
     at System.Console.get_Out()
     at System.Console.WriteLine(String value)
     at SpecFlow.NetCore.Program.PrintUsingColor(String message, ConsoleColor newColor)
     at SpecFlow.NetCore.Program.Main(String[] args)
C:\BuildAgent\work\1cdf652514f12572\backend\tests\services.SpecFlow\services.SpecFlow.csproj(92,5): error MSB3073: The command "dotnet SpecFlow.NetCore" exited with code -532462766.

Build FAILED.

C:\BuildAgent\work\1cdf652514f12572\backend\tests\services.SpecFlow\services.SpecFlow.csproj(92,5): error MSB3073: The command "dotnet SpecFlow.NetCore" exited with code -532462766.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.12
PS C:\BuildAgent\work\1cdf652514f12572\backend>
````

**Comment by smudge202** [comment] 2018-01-11 14:37
Can you print the content of `.\tests\services.Specflow\services.SpecFlow.csproj` here please

**Comment by roman-kozachenko** [comment] 2018-01-11 15:02
@smudge202 here you can find content of `services.SpecFlow.csproj` file https://gist.github.com/roman-kozachenko/3d0a08466df4d3511c8e825bfc1dd01d

**Comment by smudge202** [comment] 2018-01-11 15:37
Yeh, as suspected. SpecFlow only supports execution on full fat framework, so you'll need to change your [`targetFramework`](https://gist.github.com/roman-kozachenko/3d0a08466df4d3511c8e825bfc1dd01d#file-services-specflow-csproj-L4) to `net462` or similar.

However, at a glance, this will cause problems with your project references.

Allowed project references:

* `netcoreapp*` -> `netstandard*`
* `net*` -> `netstandard*`

It is not possible to reference `net*` -> `netcoreapp*`, so if any of your projects target `netcoreapp` then this won't work for you. However, if you're able to move the code you want to test into a `netstandard*` targeted class library instead, then both your test project (`net462`) and your application (`netcoreapp2.0`) will be able to reference the code.

Unfortunately, there *can* be differences between the `net` and `netcoreapp` implementations of `netstandard`, which *could* lead to a situation whereby your tests pass but code fails as a result of differences.

Really need the main SpecFlow project to get up to speed with the net core infrastructure; only so much we can do as part of this bridging project I'm afraid.

**Comment by aensidhe** [comment] 2018-01-11 16:51
That is strange. Why would build pass on development machine then? Do you have any ideas?

**Comment by smudge202** [comment] 2018-01-11 17:03
Hmmm, fair point, maybe I've misunderstood. Are the build agent and your dev machine running the same runtime? The current `dotnet --version` should [return `2.1.4`](https://www.microsoft.com/net/download/windows) though I see your build agent is running `2.0.3`?

**Comment by smudge202** [comment] 2018-01-11 17:10
I can see part of the problem but I don't know the full story yet. The `netcoreapp2.0` version of this project depends on [`System.Xml.XPath.XDocument` v4.0.1](https://www.nuget.org/packages/System.Xml.XPath.XDocument/4.0.1) which in turn relies on [`System.Threading` v4.0.11](https://www.nuget.org/packages/System.Threading/4.0.11).

The runtime will no doubt depend on [`System.Threading` v4.3.0](https://www.nuget.org/packages/System.Threading/4.3.0) which can be achieved if this project updates to [`System.Xml.XPath.XDocument` v4.3.0](https://www.nuget.org/packages/System.Xml.XPath.XDocument/4.3.0).

Why it is that one runtime works and another doesn't (I'm assuming you'll come back and tell me your build agent and dev machine have different runtimes) I do not know.

I also do not know why this project allows `netcoreapp2.0` because it isn't at all possible to run/install [SpecFlow itself](https://www.nuget.org/packages/specflow) on anything other than `net45` and up.

@stajs we should probably cleanup the project dependencies? Mirror specflow and only target on `net45` maybe?

**Comment by aensidhe** [comment] 2018-01-11 17:23
@smudge202 I spent quite a lot of time trying to replicate environments. After your question, I removed 'global.json' which restrict our sdk to 2.0.3 and updated both environments to 2.1.4 sdk and 2.0.5 runtime. Zero changes in behaviour. Main difference: build agent do not have visual studio installed.

**Comment by smudge202** [comment] 2018-01-11 17:24
Whilst it won't *fix* the issue, I suspect it would go away if the test project targets `net461` (`net45`+ required to run SpecFlow)?

EDIT: To better exaplin...

Despite the name of this repo/package (might be worth discussing, @stajs ) the application doesn't actually magically allow specflow to work with `netcoreapp` unfortunately. I wish we could. What it does allow is the use of the new style `csproj` that came along with netcore. I wish the *"new sytle csproj"* had a name itself so that this project could be better named.

All the application does is generate a legacy style `csproj` which is the only format that SpecFlow itself understands. Then the app goes looking for SpecFlow and tells it to run against the legacy csproj the app created (therefore performing all of the SpecFlow shenanigans like auto-generating `*.cs` from `*.feature`) before deleting the legacy style csproj the tool had created.

At that point, the normal test runner can execute (regardless of whether your runtime is `netcore` or `net`) because all that is left is a bunch of `*.cs` containing tests.

We could potentially improve the project by making it possible to have a `netcoreapp` only test project execute tests against a `netcoreapp` or `netstandard` library by hotswapping stuff all over the place. As it stands, the tool basically only works against `net45` and up, because that's the only way to get the normal SpecFlow nuget package installed.

I don't know about @stajs but certainly when I first started trying to help this project, the feeling was that it would be a shortlived *hack* because surely SpecFlow would update to netcore within a month or two. That was around 2 years ago...

**Comment by stajs** [comment] 2018-01-12 01:14
Just a quick note to acknowledge the report. I'm on vacation for the next few days and will have a better look when I get home so just setting the expectation for a slow response. 

This whole thing was supposed to be a short lived hack. Who would have thought SpecFlow would take this long to support .NET Core? I've been seriously considering writing an alternative  ...

**Comment by aensidhe** [comment] 2018-01-15 16:49
So, I did change target framework to .net 461. Nothing changes and this is very interesting. Tomorrow I'll try to install VS Community to build agent and look what changes.

**Comment by aensidhe** [comment] 2018-01-16 08:08
So, I installed latest vs 2017 and all available update on build agent, and nothing changes. I do not know, what causes it. I will continue to investigate this issue, but only on "free time" basis, sorry.

**Comment by stajs** [comment] 2018-01-16 10:38
There's quite a bit going on here...

I think the real question is, how the heck is it working on your development machine?! There is no way it should be running so the build agent is failing as expected. As noted in the [README](https://github.com/stajs/SpecFlow.NetCore#supported-frameworks):

> SpecFlow itself, and by extension this project, is currently limited to running on full .NET Framework.

Are you able to share a minimal reproduction?

Build agents shouldn't need Visual Studio installed.

Previously, when trying to restore `SpecFlow` for `netcoreapp1.1` it [resulted in an error](https://github.com/stajs/SpecFlow.NetCore/issues/49#issuecomment-325221582). Now it looks like it's been downgraded to a warning. That's disappointing.

As @smudge202 and [others have mentioned](https://github.com/stajs/SpecFlow.NetCore/issues/46#issuecomment-290440918), you should be able to mix and match .NET/.NETCoreApp projects to workaround the issue.

Does the sample project work on both your development machine and build agent?

**Comment by stajs** [comment] 2018-01-16 11:02
As an aside, the fact that this project accepts `netcoreapp2.0` is a mistake. It was ignorance when first setting up a .NET CLI tool.

https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility

> Since tools are portable applications, the user consuming the tool must have the version of the .NET Core libraries that the tool was built against in order to run the tool.
> 
> These kinds of tools have a dependency graph that is completely separate from the dependency graph of the project that uses them. The restore process first restores the project's dependencies and then restores each of the tools and their dependencies.

I naively thought that the tool should target .NETCoreApp (because why not), but that has just lead to the incorrect (and totally understandable) assumption by many people that you can use the tool in .NETCoreApp projects. After all, looking at the [nuget.org](https://www.nuget.org/packages/SpecFlow.NetCore) dependencies it kind of implies compatibility.

#66 has given me some things to think about - I'll let the thoughts settle and follow up this aside in there.

**Comment by stajs** [comment] 2018-01-16 11:09
So that leaves us with trying to discern the difference between your development machine and build agent. A minimal repro would be the best step forward from here.

**Comment by stajs** [comment] 2018-03-22 07:48
Closing as the requested repro has not been provided.

**Closed as completed by stajs** 2018-03-22 07:48 UTC
